import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Nex-Sentia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
       <AuthProvider>{children}

            <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#0F2828",
                color: "#EFF2FE",
                border: "1px solid #469F88CC",
                padding: "12px 16px",
                borderRadius: "12px",
              },
            }}
          />
       </AuthProvider>
      </body>
    </html>
  );
}
